#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

start_service() {
	[ "$(uci -q get sms_tool.general.forward_enable)" = "1" ] || return 0

	procd_open_instance
	procd_set_param command /usr/bin/c8-sms-forward run
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

reload_service() {
	stop
	start
}
